piano_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :composers
  resources :pieces

end

piano_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

piano_app/app/models/composer.rb
class Composer < ApplicationRecord
  has_many :pieces
end

piano_app/app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :composer
end

piano_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

piano_app/app/controllers/composers_controller.rb
class ComposersController < ApplicationController
  def index
    @composers = Composer.all
  end
  def show
    @composer = Composer.find(params[:id])
  end
  def new
    @composer = Composer.new
  end
  def create
    @composer = Composer.create(composer_params)
    redirect_to composers_path
  end
  def edit
    @composer = Composer.find(params[:id])
  end
  def update
    @composer = Composer.find(params[:id])

    if @composer.update(composer_params)
      redirect_to @composer
    else
      render :action => :edit
    end
  end
  def destroy
    composer = Composer.find(params[:id])
    composer.delete
    redirect_to composers_path
  end

  private

  def composer_params
    params.require(:composer).permit(:name, :bio, :image)
  end
end

piano_app/app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  def index
    @pieces = Piece.all
  end

  def show
    @piece = Piece.find(params[:id])
  end
  def new
    @piece = Piece.new
  end
  def create
    @piece = Piece.create!(piece_params)
    redirect_to composers_path
  end
  def edit
    @piece = Piece.find(params[:id])
  end
  def update
    @piece = Piece.find(params[:id])

    if @piece.update(piece_params)
      redirect_to @piece
    else
      render :action => :edit
    end
  end
  def destroy
    @piece = Piece.find(params[:id])
    @piece.delete
    redirect_to composers_path
  end

  private

  def piece_params
    params.require(:piece).permit(:name, :url, :composer_id)
  end
end

piano_app/app/helpers/application_helper.rb
module ApplicationHelper
end

piano_app/app/views/composers/_form.html.erb
<%= form_for @composer do |form| %>
  Name: <%= form.text_field :name %>
  <br />
  Bio: <%= form.text_field :bio %>
  <br />
  Image: <%= form.text_field :image %>
  <br />
  <%= form.submit %>
<% end %>

piano_app/app/views/composers/edit.html.erb
<div class="composers-container">
  <h1>Edit information about this composer</h1>
  <%= render partial: "form" %>
  <%= link_to "Back to All Composers", composers_path, class: "link" %>
</div>

piano_app/app/views/composers/index.html.erb
<div class="composers-container">
  <h1>PianoApp</h1>
  <% @composers.each do |composer| %>
  <img src="<%= composer[:image] %>" />
  <p><%= link_to composer[:name], "composers/#{composer[:id]}", class: "link" %></p>
  <% end %>
  <p><%= link_to "Add a new composer!", new_composer_path, class: "link" %></p>
</div>

piano_app/app/views/composers/new.html.erb
<div class="composers-container">
  <h1>Add a composer</h1>
  <%= render partial: "form" %>
  <%= link_to "Back to All Composers", composers_path, class: "link" %>
</div>

piano_app/app/views/composers/show.html.erb
<div class="composers-container">
  <h1><%= @composer[:name] %></h1>
  <img src="<%= @composer[:image] %>" />
  <article><%= @composer[:bio] %></article>
  <% @composer.pieces.each do |piece| %>
  <p><%= link_to piece[:name], "../pieces/#{piece[:id]}", class: "link" %></p>
  <audio controls>
  <source src="../<%= piece[:url] %>" type="audio/mpeg">
  </audio>
  <br />
  <% end %> 
  <br />
  <p><%= button_to "Add a Piece", new_piece_path, method: 'get' %><%= button_to "Edit Composer", edit_composer_path, method: 'get', class: "button" %><%= button_to "Delete Composer:(", composer_path, method: 'delete', class: "button" %></p>
  
  <p><%= link_to "Back to All Composers", composers_path, class: "link" %></p>
  
</div>

piano_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PianoApp</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Rozha+One" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

piano_app/app/views/pieces/_form.html.erb
<%= form_for @piece do |form| %>
  Name: <%= form.text_field :name %>
  <br />
  URL: <%= form.text_field :url %>
  <br />
  <%= form.select(:composer_id, Composer.all.collect {|u| [u.name, u.id]}, :prompt => 'Select Composer') %>
  <%= form.submit %>
<% end %>

piano_app/app/views/pieces/edit.html.erb
<div class="music-container">
  <h1>Edit information about this Piece</h1>
  <%= render partial: "form" %>
  <%= link_to "Back to Composer", "http://localhost:3000/composers/#{@piece.composer[:id]}", class: "link" %>
</div>

piano_app/app/views/pieces/index.html.erb
<div class="music-container">
  <h1>Music</h1>
  <% @pieces.each do |piece| %>
  <p><%= link_to piece[:name], "pieces/#{piece[:id]}", class: "link" %></p>
  <audio controls>
  <source src="<%= piece[:url] %>" type="audio/mpeg">
  </audio>
  <br />
  <% end %>
  <%= link_to "Go to Composers", composers_path, class: "link" %>
</div>

piano_app/app/views/pieces/new.html.erb
<div class="music-container">
  <h1>Add a Piece</h1>
  <%= render partial: "form" %>
  <%= link_to "Back to Composers", composers_path, class: "link" %>
</div>

piano_app/app/views/pieces/show.html.erb
<div class="music-container">
  <h1><%= @piece[:name] %></h1>
  <h3>by <%= @piece.composer[:name] %></h3>
  <audio controls>
  <source src="../<%= @piece[:url] %>" type="audio/mpeg">
  </audio>
  <br />
  <p><%= button_to "Edit Piece", edit_piece_path, method: 'get', class: "button" %><%= button_to "Delete Piece:(", piece_path, method: 'delete', class: "button" %></p>
  <br />
  <p><%= link_to "Back to Composer", "../composers/#{@piece.composer[:id]}", class: "link" %></p>
  <br />
</div>